name: Update Google Sheets Daily

on:
  schedule:
    - cron: "0 6 * * *"   # runs every day at 6 AM UTC
  workflow_dispatch:       # lets you run it manually too

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files for debugging
        run: |
          pwd
          ls -la

    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run sheet update
        env:
          SA_KEY_JSON: ${{ secrets.SA_KEY_JSON }}
          TARGET_SHEET_ID: ${{ secrets.TARGET_SHEET_ID }} 
          SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CRED }}
        run: |
          echo "$SA_KEY_JSON" > cred.json
          python Stocks-Updated-Scripts.py cred.json
